HOST = "localhost"
DATABASE_PORT = 9432
API_PORT = DATABASE_PORT + 1
POSTGRES_DATABASE = "normflix"
POSTGRES_USER = "norm"
POSTGRES_PASSWORD = "norm"
POSTGRES_CONTAINER_NAME = "normflix"
POSTGRES_VERSION = "latest"


POSTGRES_SETUP_CONN_URL = (
	f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{HOST}:{DATABASE_PORT}"
)
POSTGRES_RUN_CONN_URL = f"{POSTGRES_SETUP_CONN_URL}/{POSTGRES_DATABASE}"
